#!/usr/bin/env python3
"""
WASP_76_b_tm.py — ratri runner for WASP-76 b (TM)

Generated by generate_runner_v2.py.

Usage:
    python WASP_76_b_tm.py              # plan nights then simulate
    python WASP_76_b_tm.py --plan       # search and save night list only
    python WASP_76_b_tm.py --simulate   # load saved night list and simulate
"""

import argparse
import json
import os
import warnings
import numpy as np
from astropy.time import Time
import astropy.units as u

# Suppress ERFA/IERS warnings for dates beyond the IERS data validity range
try:
	import erfa
	warnings.filterwarnings('ignore', category=erfa.ErfaWarning)
except ImportError:
	pass
from astropy.utils.exceptions import AstropyWarning
warnings.filterwarnings('ignore', category=AstropyWarning)
import logging
logging.getLogger('astropy').setLevel(logging.ERROR)

from ratri import ratri_auto, _select_night, _OBSERVATORIES, _PWV_TIERS


# ---------------------------------------------------------------------------
# File paths
# ---------------------------------------------------------------------------

ATM_DIR       = './atm_transmission'
SPECTRA_CACHE = './spectra_cache'
PLANET_MODEL  = None
SAVEDIR_BASE  = './output/WASP_76_b_tm/'
NIGHTS_FILE   = './spectra_cache/WASP_76_b_tm_nights.json'


# ---------------------------------------------------------------------------
# Instrument
# ---------------------------------------------------------------------------

INST  = 'nlot_ccd_giano'
MODES = []
T_EXP = 300


# ---------------------------------------------------------------------------
# Observation mode
# ---------------------------------------------------------------------------

# Phase convention:
#   Phase 0    = transit centre (planet in front of star)
#   Phase ±0.5 = occultation centre (planet behind star)
#   Positive phases: post-transit, planet moving away from observer
#   Negative phases: post-occultation, planet returning toward observer
OB = 'tm'


# ---------------------------------------------------------------------------
# Search parameters
# ---------------------------------------------------------------------------

T_SEARCH_START = Time('2026-10-01 00:00:00', scale='utc')
T_SEARCH_END   = Time('2028-09-30 00:00:00', scale='utc')

# Phase window
# Transit: symmetric window centred on phase 0
PHASE_MIN    = -0.13
PHASE_MAX    = 0.13

MIN_DURATION = 1.5    # minimum observable window in hours
AIRMASS_MIN  = 1.0
AIRMASS_MAX  = 2.0


# ---------------------------------------------------------------------------
# Orbital and system parameters
# Orbital parameters: Fu et al. 2021
#   vsys (km/s) supplemented from: Ehrenreich et al. 2020
# Stellar parameters: Ehrenreich et al. 2020
# ---------------------------------------------------------------------------

MEAN_TRANSIT_BJD = 2457360.293
T0               = Time(MEAN_TRANSIT_BJD, format='jd', scale='tdb')
PERIOD           = 1.80988158 * u.day
TR_DURATION_H    = 3.7526    # hours

E          = 0.016
OMEGA      = 1.082104    # radians  (62.0 deg)
VSYS       = -1.11             # km/s
KP         = 198.56               # km/s

print(f'Kp = {KP:.2f} km/s')


# ---------------------------------------------------------------------------
# Shared keyword arguments for ratri_auto
# ---------------------------------------------------------------------------

def _common_kwargs(savedir, qual):
	return dict(
		planet_name       = 'WASP-76 b',
		star_name         = 'WASP-76',
		inst              = INST,
		modes             = MODES,
		ob                = OB,
		t_exp             = T_EXP,
		T0                = T0,
		period            = PERIOD,
		mean_transit_BJD  = MEAN_TRANSIT_BJD,
		tr_duration_h     = TR_DURATION_H,
		e                 = E,
		omega             = OMEGA,
		vsys              = VSYS,
		Kp                = KP,
		t_search_start    = T_SEARCH_START,
		t_search_end      = T_SEARCH_END,
		phase_min         = PHASE_MIN,
		phase_max         = PHASE_MAX,
		airmass_min       = AIRMASS_MIN,
		airmass_max       = AIRMASS_MAX,
		min_duration      = MIN_DURATION,
		planet_model_path = PLANET_MODEL,
		atm_dir           = ATM_DIR,
		spectra_cache_dir = SPECTRA_CACHE,
		library           = None,
		noise_seed        = 3,
		savedir           = savedir,
		qual              = qual,
	)


def _print_summary(results, savedir):
	chosen = results['chosen_night']
	orbit  = results['orbit']
	flux   = results['flux_cube']
	print(f'\nSimulation complete.')
	print(f'  Night         : {chosen["night"]}')
	print(f'  n_spectra     : {flux.shape[1]}')
	print(f'  n_orders      : {flux.shape[0]}')
	print(f'  Phase range   : [{orbit["ph"].min():+.4f}, {orbit["ph"].max():+.4f}]')
	print(f'  Airmass range : [{orbit["airmass"].min():.2f}, {orbit["airmass"].max():.2f}]')
	print(f'  Stellar T_eff : {results["stellar_params"]["teff"]:.0f} K')
	print(f'  Library used  : {results["spectrum_paths"]["library"]}')
	print(f'  Saved to      : {savedir}')


# ---------------------------------------------------------------------------
# Plan step: search for observable nights and save to JSON
# ---------------------------------------------------------------------------

def plan():
	nights = _select_night(
		target_name  = 'WASP-76 b',
		inst         = INST,
		t_start      = T_SEARCH_START,
		t_end        = T_SEARCH_END,
		T0           = T0,
		period       = PERIOD,
		phase_min    = PHASE_MIN,
		phase_max    = PHASE_MAX,
		airmass_min  = AIRMASS_MIN,
		airmass_max  = AIRMASS_MAX,
		min_duration = MIN_DURATION,
	)

	if not nights:
		print('\nNo qualifying nights found. Try adjusting the search parameters.')
		return None

	nights_json = []
	for i, n in enumerate(nights):
		nights_json.append(dict(
			rank            = i,
			night           = n['night'],
			evening_date    = n['evening_date'],
			total_hours     = n['total_hours'],
			total_hours_all = n['total_hours_all'],
			phase_str       = n['phase_str'],
			airmass_range   = list(n['airmass_range']),
			obs_start       = n['obs_start'].iso,
			obs_end         = n['obs_end'].iso,
		))

	with open(NIGHTS_FILE, 'w') as f:
		json.dump(nights_json, f, indent=2)
	print(f'\nNight list saved to {NIGHTS_FILE}')
	return nights


# ---------------------------------------------------------------------------
# Simulate step: load saved night list and simulate chosen ranks
# ---------------------------------------------------------------------------

def simulate(nights=None):
	if nights is None:
		if not os.path.exists(NIGHTS_FILE):
			print(f'Night list not found: {NIGHTS_FILE}')
			print('Run with --plan first, or without arguments to do both.')
			return
		with open(NIGHTS_FILE) as f:
			nights_json = json.load(f)

		nights = []
		for n in nights_json:
			nights.append(dict(
				rank            = n['rank'],
				night           = n['night'],
				evening_date    = n['evening_date'],
				total_hours     = n['total_hours'],
				total_hours_all = n['total_hours_all'],
				phase_str       = n['phase_str'],
				airmass_range   = tuple(n['airmass_range']),
				obs_start       = Time(n['obs_start'], scale='utc'),
				obs_end         = Time(n['obs_end'],   scale='utc'),
			))

		print(f'\nLoaded {len(nights)} qualifying nights from {NIGHTS_FILE}:')
		print(f'  {"Rank":<5} {"Night":<16} {"Obs. Hours (Total)":<22} {"Phase Coverage":<48} {"Airmass"}')
		print('  ' + '-' * 105)
		for n in nights:
			hrs_str   = f'{n["total_hours"]:.1f} ({n["total_hours_all"]:.1f})'
			phase_str = n['phase_str'].ljust(50)
			print(
				f'  {n["rank"]:<5} '
				f'{n["night"]:<16} '
				f'{hrs_str:<22}'
				f'{phase_str:<52}'
				f'[{n["airmass_range"][0]:.2f}, {n["airmass_range"][1]:.2f}]'
			)

	print(f'\nEnter rank(s) to simulate — 0-indexed, space-separated:')
	raw = input('  Ranks: ').strip()
	try:
		ranks = [int(r) for r in raw.split()]
	except ValueError:
		print('Invalid input.')
		return
	ranks = [r for r in ranks if 0 <= r < len(nights)]
	if not ranks:
		print(f'No valid ranks in range [0, {len(nights)-1}].')
		return

	site_default = _OBSERVATORIES[INST]['default_qual']
	tier_str     = '/'.join(_PWV_TIERS.keys())
	night_quals  = {}
	for rank in ranks:
		night_label = nights[rank]['night']
		raw_q = input(
			f'  Rank {rank} ({night_label}) — PWV quality '
			f'[{tier_str}, default={site_default}]: '
		).strip().lower()
		night_quals[rank] = raw_q if raw_q in _PWV_TIERS else site_default
		chosen_q = night_quals[rank]
		if not raw_q:
			print(f'    Using site default: {chosen_q}')
		elif raw_q not in _PWV_TIERS:
			print(f'    Unrecognised tier "{raw_q}", using site default: {chosen_q}')
		else:
			print(f'    PWV quality set to: {chosen_q}')

	for rank in ranks:
		evening_date = nights[rank]['evening_date']
		savedir      = f'{SAVEDIR_BASE}{evening_date}/'

		print(f'\n{"="*60}')
		print(f'Simulating rank {rank}: night {nights[rank]["night"]}')
		print(f'Output directory: {savedir}')
		print(f'{"="*60}')

		results = ratri_auto(
			**_common_kwargs(savedir=savedir, qual=night_quals[rank]),
			chosen_night = nights[rank],
		)

		if results is None:
			print(f'Rank {rank} returned no results — skipping.')
			continue

		_print_summary(results, savedir)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == '__main__':
	parser = argparse.ArgumentParser(
		description=f'ratri runner for WASP-76 b (TM)'
	)
	parser.add_argument('--plan',     action='store_true',
	                    help='Search for observable nights and save to JSON only')
	parser.add_argument('--simulate', action='store_true',
	                    help='Load saved night list and simulate (skips search)')
	args = parser.parse_args()

	if args.plan and not args.simulate:
		plan()
	elif args.simulate and not args.plan:
		simulate()
	else:
		nights = plan()
		if nights:
			simulate(nights=nights)
